name: Header Comments CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Add comments
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add comments to src/
        uses: pabio/header-comments@v1.0.5c
      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v3
